# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "app dependency"



  #
  # Tools dependency
  #

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/ecs"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "tools"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/psalm"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "tools"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/infection"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "tools"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/phparkitect"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "tools"
    labels:
      - "tool dependency"
