name: Acceptance stage

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      triggering-sha:
        required: true
        type: string
jobs:
  triggering-workflow-info:
    runs-on: ubuntu-18.04
    name: Triggering workflow info
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - name: Dump input triggering-sha
        run: echo triggering-sha ${{ inputs.triggering-sha }}
      - name: Dump Manual dispatch input sha
        run: echo manual dispatch sha ${{ github.event.inputs.sha }}
